# Each instruction in this file generates a new layer that gets pushed to your local image cache
FROM python:latest

# Identify the maintainer of an image
LABEL version="0.0.1"
LABEL maitainer="oleksii.sterlikov@gmail.com"

# Add Python Script
ADD my-script.py /

# Execute python script
CMD [ "python", "./my-script.py" ]